import React, { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { CalendarClock, CheckCircle2, CircleDashed, Clock3, MinusCircle } from 'lucide-react-native';
import type { BaselineDayRecord, BaselineReadinessRecord } from '@sarira/shared-types';
import { colors, radius, spacing } from '@sarira/design-tokens';
import { AppText, Button, Card, Chip, ErrorState, InlineNotice, Loading, ProgressBar } from '@sarira/ui';
import { AppShell } from '@/layouts/AppShell';
import { api } from '@/services/api';
import { messageFor, useBaseline } from '@/features/baseline/useBaseline';

const statusMeta = (day: BaselineDayRecord) => day.state === 'UPCOMING' ? { label: 'Belum datang', icon: Clock3, tone: 'neutral' as const } : day.completenessStatus === 'COMPLETE' ? { label: 'Lengkap', icon: CheckCircle2, tone: 'mint' as const } : day.completenessStatus === 'PARTIAL' ? { label: 'Sebagian', icon: MinusCircle, tone: 'warning' as const } : { label: 'Belum tercatat', icon: CircleDashed, tone: 'neutral' as const };

export default function BaselineJourneyScreen() {
  const { current, loading: baselineLoading, error: baselineError, reload } = useBaseline();
  const [days, setDays] = useState<BaselineDayRecord[]>([]); const [readiness, setReadiness] = useState<BaselineReadinessRecord>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  const load = useCallback(async () => { if (!current) return; setLoading(true); setError(undefined); try { const values = await api.getBaselineDays(current.baseline.id); setDays(values); if (current.day14Available) setReadiness(await api.getReadiness(current.baseline.id)); } catch (cause) { setError(messageFor(cause)); } finally { setLoading(false); } }, [current]);
  useEffect(() => {
    if (!current) return;
    const timer = setTimeout(() => void load(), 0);
    return () => clearTimeout(timer);
  }, [current, load]);
  return <AppShell title="Perjalanan Baseline" subtitle="14 hari berdasarkan kalender lokal">
    {baselineLoading ? <Loading label="Memuat baseline…" /> : baselineError ? <ErrorState description={baselineError} onRetry={() => void reload()} /> : !current ? <ErrorState title="Baseline belum dimulai" description="Buka Starter Journey untuk memulai." /> : <>
      <Card tone="dark" style={styles.hero}><View style={styles.row}><View style={styles.flex}><AppText variant="eyebrow" style={styles.lime}>BASELINE · {current.baseline.timezone}</AppText><AppText variant="h1" style={styles.white}>Hari {Math.min(current.baseline.currentDay, current.baseline.targetDays)} dari {current.baseline.targetDays}</AppText><AppText variant="body" style={styles.muted}>{current.completeness.completedDays} hari lengkap · kelengkapan data {current.completeness.score}%</AppText></View><CalendarClock size={42} color={colors.lime} /></View><ProgressBar value={Math.min(current.baseline.currentDay, current.baseline.targetDays)} max={current.baseline.targetDays} tone="lime" label={`Hari ${Math.min(current.baseline.currentDay, current.baseline.targetDays)} dari ${current.baseline.targetDays}`} /></Card>
      <InlineNotice title="Histori dapat diperbaiki" text="Selama baseline belum ditutup, hari sebelumnya dapat dilihat, dilengkapi, dan diedit. Hari terlewat tidak menggeser timeline." tone="info" />
      {error ? <ErrorState description={error} onRetry={() => void load()} /> : loading ? <Loading label="Memuat 14 hari…" /> : <View style={styles.calendar}>{days.map((day) => { const meta = statusMeta(day); const Icon = meta.icon; return <Pressable key={day.dayIndex} accessibilityRole="button" accessibilityLabel={`Hari ${day.dayIndex}, ${day.localDate}, ${meta.label}${day.state === 'TODAY' ? ', hari ini' : ''}`} disabled={day.state === 'UPCOMING'} onPress={() => router.push({ pathname: '/baseline-day' as never, params: { day: String(day.dayIndex) } } as never)} style={({ pressed }) => [styles.day, day.state === 'TODAY' && styles.today, day.state === 'UPCOMING' && styles.upcoming, pressed && { opacity: 0.72 }]}><View style={styles.row}><View style={styles.dayNumber}><AppText variant="h3">{day.dayIndex}</AppText></View><Icon size={22} color={day.completenessStatus === 'COMPLETE' ? colors.success : day.completenessStatus === 'PARTIAL' ? colors.warning : colors.textMuted} /></View><AppText variant="label">Hari {day.dayIndex}</AppText><AppText variant="caption">{day.localDate}</AppText><View style={styles.chips}><Chip label={meta.label} tone={meta.tone} />{day.state === 'TODAY' ? <Chip label="HARI INI" tone="lime" /> : null}</View><AppText variant="caption">{day.categoryCount} dari 4 kategori tercatat</AppText></Pressable>; })}</View>}
      {current.day7Available && !current.day14Available ? <Card tone="blue" style={styles.row}><View style={styles.flex}><AppText variant="h3">Checkpoint Hari 7 tersedia</AppText><AppText variant="body">Lihat ringkasan deskriptif dan beri feedback tentang pengalaman mencatat.</AppText></View><Button label="Buka checkpoint" variant="secondary" onPress={() => router.push('/day-7-checkpoint' as never)} /></Card> : null}
      {readiness ? <Card tone={readiness.status === 'READY' ? 'mint' : 'cream'} style={styles.stack}><View style={styles.row}><View style={styles.flex}><AppText variant="eyebrow">DAY-14 READINESS</AppText><AppText variant="h2">{readiness.status.replaceAll('_', ' ')}</AppText></View><Chip label={`${readiness.completenessScore}% DATA`} tone={readiness.status === 'READY' ? 'mint' : 'warning'} /></View><AppText variant="body">{readiness.recommendation}</AppText><AppText variant="caption">Pattern Map final belum dibuat. Threshold ini merupakan konfigurasi development dan memerlukan validasi product/expert.</AppText>{readiness.status === 'READY' ? <Button label="Tutup baseline" variant="primary" onPress={() => void api.completeBaseline(current.baseline.id).then(() => reload())} /> : <InlineNotice title="Tracking dapat dilanjutkan" text={`Perpanjangan teknis maksimal ${current.baseline.extensionDays} hari tersedia, tidak berjalan tanpa batas.`} tone="warning" />}</Card> : null}
    </>}
  </AppShell>;
}

const styles = StyleSheet.create({ hero: { gap: spacing.lg, borderColor: colors.primaryDark, padding: spacing.xl }, white: { color: colors.white }, lime: { color: colors.lime }, muted: { color: '#C8D6CC' }, flex: { flex: 1, gap: 4 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md, flexWrap: 'wrap' }, stack: { gap: spacing.md }, calendar: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, day: { width: 190, minHeight: 180, borderRadius: radius.card, backgroundColor: colors.white, borderWidth: 2, borderColor: colors.border, padding: spacing.md, gap: spacing.xs }, today: { borderColor: colors.primary, backgroundColor: colors.softMint }, upcoming: { opacity: 0.55 }, dayNumber: { width: 44, height: 44, borderRadius: 16, backgroundColor: colors.surfaceSoft, alignItems: 'center', justifyContent: 'center' }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs } });
