import React, { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, Check, ChefHat, ChevronLeft, ChevronRight, Timer } from 'lucide-react-native';
import type { DailyMealPlanRecord, NutrientCode } from '@sarira/shared-types';
import { colors, radius, spacing } from '@sarira/design-tokens';
import { AppText, Button, Card, Chip, ErrorState, InlineNotice, Loading, ProgressBar } from '@sarira/ui';
import { AppShell } from '@/layouts/AppShell';
import { messageFor } from '@/features/baseline/useBaseline';
import { api } from '@/services/api';

const nutritionLabels: Partial<Record<NutrientCode, string>> = { ENERGY_KCAL: 'Energi', PROTEIN_G: 'Protein', FIBER_G: 'Serat', SODIUM_MG: 'Natrium' };
const nutritionValue = (value: number | null | undefined, code: NutrientCode, multiplier: number) => value === null || value === undefined ? 'belum tersedia' : `${Math.round(value * multiplier * 10) / 10} ${code === 'ENERGY_KCAL' ? 'kcal' : code.endsWith('_MG') ? 'mg' : 'g'}`;

export default function CookingScreen() {
  const { planId, itemId } = useLocalSearchParams<{ planId?: string; itemId?: string }>(); const [plan, setPlan] = useState<DailyMealPlanRecord>(); const [stepIndex, setStepIndex] = useState(0); const [checked, setChecked] = useState<Record<string, boolean>>({}); const [servings, setServings] = useState(1); const [fraction, setFraction] = useState<1 | 0.75 | 0.5 | 0.25>(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  const item = useMemo(() => plan?.items.find((value) => value.id === itemId), [itemId, plan]); const steps = item?.recipe.currentVersion.steps ?? []; const currentStep = steps[stepIndex];
  useEffect(() => { if (!planId || !itemId) return; const timer = setTimeout(async () => { try { await api.startCooking(planId, itemId); setPlan(await api.getMealPlan(planId)); } catch (cause) { setError(messageFor(cause)); } finally { setLoading(false); } }, 0); return () => clearTimeout(timer); }, [itemId, planId]);
  const consume = async () => { if (!planId || !itemId) return; setLoading(true); try { const result = await api.consumeMealPlanItem(planId, itemId, fraction); setPlan(result.plan); } catch (cause) { setError(messageFor(cause)); } finally { setLoading(false); } };
  return <AppShell title="Cooking Mode" subtitle="Langkah demi langkah dengan snapshot resep">
    <Button label="Kembali ke plan" icon={ArrowLeft} variant="ghost" onPress={() => router.push('/guided-meal' as never)} />
    {loading && !plan ? <Loading label="Menyiapkan Cooking Mode…" /> : error ? <ErrorState description={error} /> : !item ? <ErrorState title="Menu tidak ditemukan" description="Item plan mungkin sudah diganti." /> : <>
      <Card tone="dark" style={styles.hero}><View style={styles.row}><View style={styles.flex}><AppText variant="eyebrow" style={styles.lime}>COOKING MODE · {item.status}</AppText><AppText variant="h1" style={styles.white}>{item.recipe.name}</AppText><AppText variant="body" style={styles.muted}>{item.recipe.currentVersion.prepTimeMinutes + item.recipe.currentVersion.cookTimeMinutes} menit · {item.recipe.currentVersion.difficulty} · versi {item.recipe.currentVersion.version}</AppText></View><ChefHat size={48} color={colors.lime} /></View></Card>
      {item.status === 'CONSUMED' ? <InlineNotice title="Sudah dikonsumsi" text="Konsumsi telah tercatat dan pemanggilan ulang tidak membuat MealLog ganda." tone="success" /> : null}
      <View style={styles.layout}><Card style={styles.ingredients}><View style={styles.row}><AppText variant="h2">Checklist bahan</AppText><View style={styles.chips}>{([0.5, 1, 1.5, 2] as const).map((value) => <Chip key={value} label={`${value}×`} selected={servings === value} onPress={() => setServings(value)} />)}</View></View>{item.recipe.currentVersion.ingredients.map((ingredient) => <Pressable key={ingredient.id} accessibilityRole="checkbox" accessibilityState={{ checked: Boolean(checked[ingredient.id]) }} accessibilityLabel={`${ingredient.foodName}, ${ingredient.quantity * servings} porsi`} onPress={() => setChecked((value) => ({ ...value, [ingredient.id]: !value[ingredient.id] }))} style={({ pressed }) => [styles.checkline, pressed && { opacity: 0.7 }]}><View style={[styles.check, checked[ingredient.id] && styles.checked]}>{checked[ingredient.id] ? <Check size={17} color={colors.primaryDark} /> : null}</View><View style={styles.flex}><AppText variant="label">{ingredient.foodName}</AppText><AppText variant="caption">{Math.round(ingredient.quantity * servings * 100) / 100} porsi{ingredient.gramAmount ? ` · ${Math.round(ingredient.gramAmount * servings)} g` : ''}</AppText></View></Pressable>)}<View style={styles.chips}>{(['ENERGY_KCAL', 'PROTEIN_G', 'FIBER_G', 'SODIUM_MG'] as const).map((code) => <Chip key={code} label={`${nutritionLabels[code]} · ${nutritionValue(item.recipe.currentVersion.nutrition?.perServing[code], code, servings)}`} tone="mint" />)}</View><AppText variant="caption">Preview bahan dan nutrisi mengikuti penyesuaian porsi memasak; catatan konsumsi tetap memakai persentase yang dikonfirmasi setelah makan.</AppText></Card>
      <Card tone="lime" style={styles.steps}><View style={styles.row}><AppText variant="eyebrow">LANGKAH {stepIndex + 1} DARI {Math.max(steps.length, 1)}</AppText>{currentStep?.timerSeconds ? <Chip label={`${Math.ceil(currentStep.timerSeconds / 60)} menit`} tone="warning" /> : null}</View><ProgressBar value={stepIndex + 1} max={Math.max(steps.length, 1)} label={`Langkah ${stepIndex + 1} dari ${steps.length}`} /><View style={styles.stepBody}>{currentStep?.timerSeconds ? <Timer size={38} color={colors.primary} /> : <ChefHat size={38} color={colors.primary} />}<AppText variant="h2">{currentStep?.instruction ?? 'Langkah belum tersedia.'}</AppText><AppText variant="body">Berpindah langkah tidak mengubah catatan nutrisi atau status konsumsi.</AppText></View><View style={styles.row}><Button label="Sebelumnya" icon={ChevronLeft} variant="secondary" disabled={stepIndex === 0} onPress={() => setStepIndex((value) => Math.max(0, value - 1))} /><Button label="Berikutnya" icon={ChevronRight} variant="primary" disabled={stepIndex >= steps.length - 1} onPress={() => setStepIndex((value) => Math.min(steps.length - 1, value + 1))} /></View></Card></View>
      {item.status !== 'CONSUMED' ? <Card tone="mint" style={styles.consume}><View style={styles.flex}><AppText variant="h3">Konfirmasi setelah makan</AppText><AppText variant="body">Pilih berapa bagian dari satu porsi plan yang benar-benar dikonsumsi.</AppText></View><View style={styles.chips}>{([1, 0.75, 0.5, 0.25] as const).map((value) => <Chip key={value} label={`${value * 100}%`} selected={fraction === value} onPress={() => setFraction(value)} />)}</View><Button label="Tandai dikonsumsi" icon={Check} variant="lime" loading={loading} onPress={() => void consume()} /></Card> : null}
    </>}
  </AppShell>;
}

const styles = StyleSheet.create({ hero: { padding: spacing.xl }, white: { color: colors.white }, lime: { color: colors.lime }, muted: { color: '#C8D6CC' }, flex: { flex: 1, minWidth: 0, gap: 4 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: spacing.sm }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, layout: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'stretch', gap: spacing.md }, ingredients: { flex: 0.8, minWidth: 280, gap: spacing.md }, steps: { flex: 1.3, minWidth: 300, gap: spacing.lg }, checkline: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border }, check: { width: 30, height: 30, borderRadius: 9, borderWidth: 2, borderColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, checked: { backgroundColor: colors.lime }, stepBody: { minHeight: 220, alignItems: 'center', justifyContent: 'center', gap: spacing.md, padding: spacing.lg, borderRadius: radius.card, backgroundColor: colors.white }, consume: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.md } });
