import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { Archive, Calculator, Copy, Plus, RefreshCw, Search, Shuffle, Trash2 } from 'lucide-react-native';
import type { FlexKitchenIngredientInput, FlexKitchenPreviewRecord, FoodItemRecord, FoodSubstitutionRecord, NutrientCode, RecipeRecord } from '@sarira/shared-types';
import { colors, radius, spacing } from '@sarira/design-tokens';
import { AppText, Button, Card, Chip, ErrorState, Field, InlineNotice, Loading } from '@sarira/ui';
import { AppShell } from '@/layouts/AppShell';
import { useBaseline, messageFor } from '@/features/baseline/useBaseline';
import { api } from '@/services/api';

type BuilderIngredient = FlexKitchenIngredientInput & { key: string; foodName: string; servings?: FoodItemRecord['servings'] };
const nutrientLabels: Partial<Record<NutrientCode, string>> = { ENERGY_KCAL: 'Energi', PROTEIN_G: 'Protein', FIBER_G: 'Serat', SODIUM_MG: 'Natrium', SUGAR_G: 'Gula', SATURATED_FAT_G: 'Lemak jenuh' };
const format = (amount: number | null | undefined, code: NutrientCode) => amount === null || amount === undefined ? 'belum tersedia' : `${Math.round(amount * 10) / 10} ${code === 'ENERGY_KCAL' ? 'kcal' : code.endsWith('_MG') ? 'mg' : 'g'}`;

export default function FlexKitchenScreen() {
  const { current, loading: baselineLoading, error: baselineError, reload: reloadBaseline } = useBaseline(); const [query, setQuery] = useState(''); const [foods, setFoods] = useState<FoodItemRecord[]>([]); const [ingredients, setIngredients] = useState<BuilderIngredient[]>([]); const [servings, setServings] = useState('2'); const [customName, setCustomName] = useState(''); const [recipeName, setRecipeName] = useState('Resep dapur saya'); const [editingId, setEditingId] = useState<string>(); const [preview, setPreview] = useState<FlexKitchenPreviewRecord>(); const [substitutions, setSubstitutions] = useState<FoodSubstitutionRecord[]>([]); const [personal, setPersonal] = useState<RecipeRecord[]>([]); const [consumedMessage, setConsumedMessage] = useState<string>(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>();
  const loadPersonal = useCallback(async () => { try { setPersonal(await api.getPersonalRecipes()); } catch { setPersonal([]); } }, []);
  useEffect(() => { const timer = setTimeout(async () => { try { setFoods((await api.searchFoods({ q: query || undefined, pageSize: 15 })).items); } catch (cause) { setError(messageFor(cause)); } }, 300); return () => clearTimeout(timer); }, [query]);
  useEffect(() => { const timer = setTimeout(() => void loadPersonal(), 0); return () => clearTimeout(timer); }, [loadPersonal]);
  const payloadIngredients = useMemo(() => ingredients.map(({ key: _key, foodName: _foodName, servings: _servings, ...item }) => item), [ingredients]);
  useEffect(() => { if (!current || ingredients.length === 0 || Number(servings) <= 0) return; const timer = setTimeout(async () => { setLoading(true); try { setPreview(await api.previewFlexKitchen({ localDate: current.localDate, servings: Number(servings), ingredients: payloadIngredients })); setError(undefined); } catch (cause) { setError(messageFor(cause)); } finally { setLoading(false); } }, 380); return () => clearTimeout(timer); }, [current, ingredients.length, payloadIngredients, servings]);
  const addFood = (food: FoodItemRecord) => { const serving = food.servings.find((item) => item.defaultServing) ?? food.servings[0]; if (!serving) return; setIngredients((values) => [...values, { key: crypto.randomUUID(), foodItemId: food.id, servingId: serving.id, quantity: 1, foodName: food.name, servings: food.servings }]); };
  const addCustom = () => { if (customName.trim().length < 2) return; setIngredients((values) => [...values, { key: crypto.randomUUID(), customName: customName.trim(), quantity: 1, foodName: customName.trim() }]); setCustomName(''); };
  const updateQuantity = (key: string, delta: number) => setIngredients((values) => values.map((item) => item.key === key ? { ...item, quantity: Math.max(0.25, Math.round((item.quantity + delta) * 100) / 100) } : item));
  const cycleServing = (key: string) => setIngredients((values) => values.map((item) => { if (item.key !== key || !item.servings?.length) return item; const currentIndex = Math.max(0, item.servings.findIndex((serving) => serving.id === item.servingId)); const next = item.servings[(currentIndex + 1) % item.servings.length]!; return { ...item, servingId: next.id }; }));
  const remove = (key: string) => { const next = ingredients.filter((item) => item.key !== key); setIngredients(next); if (next.length === 0) setPreview(undefined); };
  const findSubstitutions = async (ingredient: BuilderIngredient) => { if (!current) return; setLoading(true); try { setSubstitutions(await api.getSubstitutions({ localDate: current.localDate, ingredient: { foodItemId: ingredient.foodItemId, servingId: ingredient.servingId, quantity: ingredient.quantity } })); } catch (cause) { setError(messageFor(cause)); } finally { setLoading(false); } };
  const applySubstitution = (value: FoodSubstitutionRecord) => { setIngredients((items) => items.map((item) => item.foodItemId === value.original.foodItemId ? { key: item.key, foodItemId: value.replacement.foodItemId, servingId: value.replacement.servingId, quantity: value.replacement.quantity, foodName: value.replacement.foodName, servings: value.replacement.food?.servings } : item)); setSubstitutions([]); };
  const save = async () => { if (!preview) return; setLoading(true); try { const input = { name: recipeName, description: 'Resep pribadi dari Flex Kitchen.', servings: Number(servings), prepTimeMinutes: 5, cookTimeMinutes: 15, difficulty: 'EASY' as const, estimatedCostCategory: 'MEDIUM' as const, cookingMethod: 'OTHER' as const, mealTypes: ['LUNCH', 'DINNER'] as ('LUNCH' | 'DINNER')[], ingredients: payloadIngredients, steps: [{ instruction: 'Siapkan seluruh bahan.' }, { instruction: 'Masak sesuai kebutuhan dan periksa kematangan.' }] }; if (editingId) await api.updatePersonalRecipe(editingId, input); else await api.savePersonalRecipe(input); setEditingId(undefined); await loadPersonal(); } catch (cause) { setError(messageFor(cause)); } finally { setLoading(false); } };
  const edit = (recipe: RecipeRecord) => { setEditingId(recipe.id); setRecipeName(recipe.name); setServings(String(recipe.currentVersion.servings)); setIngredients(recipe.currentVersion.ingredients.map((item) => ({ key: crypto.randomUUID(), ...(item.foodItemId ? { foodItemId: item.foodItemId } : {}), ...(item.servingId ? { servingId: item.servingId } : {}), ...(item.customName ? { customName: item.customName } : {}), ...(item.userNutrition ? { userNutrition: item.userNutrition } : {}), quantity: item.quantity, foodName: item.foodName, servings: item.food?.servings }))); setSubstitutions([]); };
  const consume = async () => { if (!current || !preview) return; setLoading(true); setConsumedMessage(undefined); try { const value = await api.consumeFlexKitchen({ localDate: current.localDate, recipeName, mealType: 'LUNCH', servings: Number(servings), fraction: 1, ingredients: payloadIngredients }); setConsumedMessage(`Satu porsi tercatat pada MealLog (${value.nutrition.itemCount} item nutrisi hari ini).`); } catch (cause) { setError(messageFor(cause)); } finally { setLoading(false); } };
  const duplicate = async (id: string) => { await api.duplicatePersonalRecipe(id); await loadPersonal(); };
  const archive = async (id: string) => { await api.archivePersonalRecipe(id); await loadPersonal(); };
  return <AppShell title="Flex Kitchen" subtitle="Susun recipe dengan kalkulasi nutrisi real-time">
    <Card tone="dark" style={styles.hero}><View style={styles.row}><View style={styles.flex}><AppText variant="eyebrow" style={styles.lime}>FLEX KITCHEN · REAL</AppText><AppText variant="h1" style={styles.white}>Masak dari bahan yang kamu pilih.</AppText><AppText variant="body" style={styles.muted}>Tambah, hapus, atau ubah porsi bahan. Mesin nutrisi Phase 5 menghitung ulang tanpa AI.</AppText></View><Calculator size={46} color={colors.lime} /></View></Card>
    {baselineLoading ? <Loading label="Memuat profil…" /> : baselineError ? <ErrorState description={baselineError} onRetry={() => void reloadBaseline()} /> : !current ? <ErrorState title="Baseline belum tersedia" description="Mulai Starter Journey terlebih dahulu." /> : <>
      {error ? <InlineNotice title="Belum berhasil" text={error} tone="danger" /> : null}
      <View style={styles.layout}><View style={styles.builder}><Card style={styles.card}><View style={styles.row}><View style={styles.flex}><AppText variant="h2">1. Tambah bahan</AppText><AppText variant="caption">Cari database server-side atau tambahkan bahan custom tanpa mengarang nutrisi.</AppText></View><Search size={24} color={colors.primary} /></View><Field label="Cari bahan" value={query} onChangeText={setQuery} placeholder="Nasi, tempe, bayam…" /><View style={styles.foodGrid}>{foods.map((food) => <Pressable key={food.id} accessibilityRole="button" accessibilityLabel={`Tambahkan ${food.name}`} onPress={() => addFood(food)} style={({ pressed }) => [styles.food, pressed && styles.pressed]}><View style={styles.flex}><AppText variant="label">{food.name}</AppText><AppText variant="caption">{food.category} · {food.servings[0]?.label}</AppText></View><Plus size={20} color={colors.primary} /></Pressable>)}</View><View style={styles.row}><View style={styles.flex}><Field label="Bahan custom" value={customName} onChangeText={setCustomName} placeholder="Nama bahan belum ada" /></View><Button label="Tambah unknown" icon={Plus} variant="secondary" disabled={customName.trim().length < 2} onPress={addCustom} /></View></Card>
      <Card tone="cream" style={styles.card}><View style={styles.row}><AppText variant="h2">2. Komposisi recipe</AppText><Chip label={`${ingredients.length} BAHAN`} /></View>{ingredients.length === 0 ? <AppText variant="body">Pilih bahan untuk memulai.</AppText> : ingredients.map((ingredient) => { const activeServing = ingredient.servings?.find((item) => item.id === ingredient.servingId); return <View key={ingredient.key} style={styles.ingredient}><View style={styles.flex}><AppText variant="label">{ingredient.foodName}</AppText><AppText variant="caption">{ingredient.customName ? 'Nutrisi UNKNOWN' : 'Database Phase 5'} · {ingredient.quantity} porsi · {activeServing?.label ?? 'serving custom'}</AppText></View><Button label="−" variant="secondary" onPress={() => updateQuantity(ingredient.key, -0.25)} /><Button label="+" variant="secondary" onPress={() => updateQuantity(ingredient.key, 0.25)} />{ingredient.foodItemId ? <Button label={`Porsi: ${activeServing?.label ?? 'pilih'}`} variant="secondary" onPress={() => cycleServing(ingredient.key)} /> : null}{ingredient.foodItemId ? <Button label="Ganti" icon={Shuffle} variant="ghost" onPress={() => void findSubstitutions(ingredient)} /> : null}<Button label="Hapus" icon={Trash2} variant="danger" onPress={() => remove(ingredient.key)} /></View>; })}<Field label="Jumlah porsi recipe" value={servings} onChangeText={setServings} keyboardType="decimal-pad" /></Card>
      {substitutions.length ? <Card tone="blue" style={styles.card}><AppText variant="h3">Preview substitusi · konfirmasi diperlukan</AppText>{substitutions.map((value) => <View key={value.replacement.foodItemId} style={styles.substitution}><View style={styles.flex}><AppText variant="label">{value.original.foodName} → {value.replacement.foodName}</AppText><AppText variant="caption">Protein {format(value.before.PROTEIN_G, 'PROTEIN_G')} → {format(value.after.PROTEIN_G, 'PROTEIN_G')}</AppText><AppText variant="caption">Natrium {format(value.before.SODIUM_MG, 'SODIUM_MG')} → {format(value.after.SODIUM_MG, 'SODIUM_MG')} · similarity {value.score}%</AppText></View><Button label="Konfirmasi" variant="lime" onPress={() => applySubstitution(value)} /></View>)}</Card> : null}</View>
      <View style={styles.summary}><Card tone="mint" style={styles.card}><View style={styles.row}><AppText variant="h2">Nutrisi real-time</AppText>{loading ? <RefreshCw size={20} color={colors.primary} /> : <Chip label={preview?.nutrition.complete ? 'DATA LENGKAP' : 'DATA TIDAK LENGKAP'} tone={preview?.nutrition.complete ? 'mint' : 'warning'} />}</View>{preview ? <><View style={styles.metrics}>{(['ENERGY_KCAL', 'PROTEIN_G', 'FIBER_G', 'SODIUM_MG', 'SUGAR_G', 'SATURATED_FAT_G'] as const).map((code) => <View key={code} style={styles.metric}><AppText variant="caption">{nutrientLabels[code]} · per porsi</AppText><AppText variant="h3">{format(preview.nutrition.perServing[code], code)}</AppText></View>)}</View>{preview.nutrition.complete ? null : <InlineNotice title="Data tidak lengkap" text="Nilai UNKNOWN tetap unknown dan tidak dianggap nol." tone="warning" />}</> : <AppText variant="body">Ringkasan muncul setelah bahan ditambahkan.</AppText>}</Card>
      <Card style={styles.card}><AppText variant="h3">Dampak ke kebutuhan hari ini</AppText>{preview ? <View style={styles.chips}>{(['PROTEIN_G', 'FIBER_G', 'SODIUM_MG', 'ENERGY_KCAL'] as const).map((code) => <Chip key={code} label={`${nutrientLabels[code]} +${format(preview.impact[code], code)}`} tone={code === 'SODIUM_MG' ? 'warning' : 'mint'} />)}</View> : null}<AppText variant="caption">Ini pendamping program, bukan diagnosis atau resep medis.</AppText></Card>
      <Card tone="lime" style={styles.card}><AppText variant="h3">Saran penyesuaian deterministik</AppText>{preview?.suggestions.length ? preview.suggestions.map((suggestion) => <View key={suggestion.reasonCode} style={styles.suggestion}><AppText variant="label">{suggestion.reasonCode.replaceAll('_', ' ')}</AppText><AppText variant="body">{suggestion.message}</AppText>{suggestion.candidateFood ? <Chip label={`Kandidat: ${suggestion.candidateFood.name}`} tone="mint" /> : null}</View>) : <AppText variant="body">Belum ada saran utama.</AppText>}</Card>
      <Card tone="soft" style={styles.card}><AppText variant="h3">{editingId ? 'Edit Resep Saya' : 'Simpan atau konsumsi recipe'}</AppText><Field label="Nama recipe" value={recipeName} onChangeText={setRecipeName} />{consumedMessage ? <InlineNotice title="Konsumsi tercatat" text={consumedMessage} tone="success" /> : null}<Button label={editingId ? 'Simpan versi baru' : 'Simpan recipe private'} icon={Plus} variant="lime" loading={loading} disabled={!preview || recipeName.trim().length < 2} onPress={() => void save()} /><Button label="Tandai 1 porsi dikonsumsi" variant="secondary" loading={loading} disabled={!preview || recipeName.trim().length < 2} onPress={() => void consume()} /></Card></View></View>
      <Card style={styles.card}><View style={styles.row}><View><AppText variant="eyebrow">PERSONAL RECIPE · PRIVATE</AppText><AppText variant="h2">Resep Saya</AppText></View><Chip label={`${personal.length} RECIPE`} /></View>{personal.length === 0 ? <AppText variant="body">Belum ada resep pribadi.</AppText> : personal.map((recipe) => <View key={recipe.id} style={styles.personal}><View style={styles.flex}><AppText variant="label">{recipe.name}</AppText><AppText variant="caption">Versi {recipe.currentVersion.version} · {recipe.currentVersion.ingredients.length} bahan · private</AppText></View><Button label="Buka" variant="ghost" onPress={() => router.push(`/recipe-detail?id=${recipe.id}` as never)} /><Button label="Edit" variant="secondary" onPress={() => edit(recipe)} /><Button label="Duplicate" icon={Copy} variant="secondary" onPress={() => void duplicate(recipe.id)} /><Button label="Archive" icon={Archive} variant="danger" onPress={() => void archive(recipe.id)} /></View>)}</Card>
    </>}
  </AppShell>;
}

const styles = StyleSheet.create({ hero: { padding: spacing.xl }, white: { color: colors.white }, lime: { color: colors.lime }, muted: { color: '#C8D6CC' }, flex: { flex: 1, minWidth: 0, gap: 4 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: spacing.sm }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, layout: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-start', gap: spacing.md }, builder: { flex: 1.4, minWidth: 320, gap: spacing.md }, summary: { flex: 0.9, minWidth: 290, gap: spacing.md, position: 'relative' }, card: { gap: spacing.md }, foodGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, food: { width: '48%', minWidth: 150, minHeight: 70, borderWidth: 1, borderColor: colors.border, borderRadius: radius.input, padding: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.xs, backgroundColor: colors.white }, pressed: { opacity: 0.7 }, ingredient: { minHeight: 70, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.xs, borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: spacing.xs }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, metric: { width: '48%', minWidth: 120, padding: spacing.sm, borderRadius: radius.input, backgroundColor: colors.white, gap: 3 }, suggestion: { borderTopWidth: 1, borderTopColor: 'rgba(0,0,0,0.1)', paddingTop: spacing.sm, gap: 4 }, substitution: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.xs }, personal: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.sm, minHeight: 70, borderBottomWidth: 1, borderBottomColor: colors.border } });
