import React, { useCallback, useEffect, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { ChefHat, Clock3, RefreshCw, Replace, Utensils } from 'lucide-react-native';
import type { DailyMealPlanRecord, MealAlternativeRecord, MealPlanItemRecord, NutrientCode } from '@sarira/shared-types';
import { colors, spacing } from '@sarira/design-tokens';
import { AppText, Button, Card, Chip, ErrorState, InlineNotice, Loading, ProgressBar } from '@sarira/ui';
import { AppShell } from '@/layouts/AppShell';
import { useBaseline, messageFor } from '@/features/baseline/useBaseline';
import { api } from '@/services/api';

const mealLabels = { BREAKFAST: 'Sarapan', LUNCH: 'Makan siang', DINNER: 'Makan malam', SNACK: 'Camilan', OTHER: 'Lainnya' } as const;
const nutrientLabels: Partial<Record<NutrientCode, string>> = { ENERGY_KCAL: 'Energi', PROTEIN_G: 'Protein', FIBER_G: 'Serat', SODIUM_MG: 'Natrium' };
const format = (value: number | null | undefined, code: NutrientCode) => value === null || value === undefined ? 'belum tersedia' : `${Math.round(value * 10) / 10} ${code === 'ENERGY_KCAL' ? 'kcal' : code.endsWith('_MG') ? 'mg' : 'g'}`;

function PlanCard({ plan, item, selected, onSelect, onReload }: { plan: DailyMealPlanRecord; item: MealPlanItemRecord; selected: boolean; onSelect: () => void; onReload: () => Promise<void> }) {
  const [alternatives, setAlternatives] = useState<MealAlternativeRecord[]>(); const [busy, setBusy] = useState(false); const [fraction, setFraction] = useState<1 | 0.75 | 0.5 | 0.25>(1); const nutrition = item.recipe.currentVersion.nutrition?.perServing;
  const loadAlternatives = async () => { setBusy(true); try { setAlternatives(await api.getMealAlternatives(plan.id, item.id)); } finally { setBusy(false); } };
  const replace = async (recipeId: string) => { setBusy(true); try { await api.replaceMeal(plan.id, item.id, { recipeId, reason: 'VARIETY' }); setAlternatives(undefined); await onReload(); } finally { setBusy(false); } };
  const consume = async () => { setBusy(true); try { await api.consumeMealPlanItem(plan.id, item.id, fraction); await onReload(); } finally { setBusy(false); } };
  return <Card tone={selected ? 'lime' : undefined} style={styles.card} accessibilityLabel={`${mealLabels[item.mealType]}, ${item.recipe.name}, status ${item.status}`}>
    <View style={styles.row}><View style={styles.flex}><AppText variant="eyebrow">{mealLabels[item.mealType]} · {item.recommendationFit} FIT</AppText><AppText variant="h3">{item.recipe.name}</AppText></View><Chip label={item.status} tone={item.status === 'CONSUMED' ? 'mint' : item.status === 'COOKING' ? 'warning' : 'neutral'} /></View>
    <View style={styles.chips}><Chip label={`${item.recipe.currentVersion.prepTimeMinutes + item.recipe.currentVersion.cookTimeMinutes} menit`} /><Chip label={item.recipe.currentVersion.difficulty} /><Chip label={`Biaya ${item.recipe.currentVersion.estimatedCostCategory}`} /></View>
    <View style={styles.chips}><Chip label={format(nutrition?.ENERGY_KCAL, 'ENERGY_KCAL')} tone="neutral" /><Chip label={`Protein ${format(nutrition?.PROTEIN_G, 'PROTEIN_G')}`} tone="mint" /><Chip label={`Serat ${format(nutrition?.FIBER_G, 'FIBER_G')}`} /></View>
    <AppText variant="caption">Dipilih karena {item.reasonCodes.map((code) => code.toLocaleLowerCase('id-ID').replaceAll('_', ' ')).join(', ')}. Fit menunjukkan kecocokan constraint, bukan keyakinan medis.</AppText>
    {item.recipe.eligibility?.allergenMessage ? <InlineNotice title="Data alergen" text={item.recipe.eligibility.allergenMessage} tone="warning" /> : null}
    <View style={styles.actions}><Button label="Lihat resep" variant="secondary" onPress={() => router.push(`/recipe-detail?id=${item.recipe.id}` as never)} /><Button label="Pilih" variant="ghost" onPress={onSelect} />{item.status !== 'CONSUMED' ? <Button label="Ganti menu" icon={Replace} variant="secondary" loading={busy} onPress={() => void loadAlternatives()} /> : null}</View>
    {alternatives ? <View style={styles.alternatives}><AppText variant="label">Alternatif eligible</AppText>{alternatives.length === 0 ? <AppText variant="caption">Belum ada alternatif lain yang lolos constraint.</AppText> : alternatives.map((alternative) => <View key={alternative.recipe.id} style={styles.alternative}><View style={styles.flex}><AppText variant="label">{alternative.recipe.name}</AppText><AppText variant="caption">{alternative.differenceMessage} · Fit {alternative.recommendationFit}</AppText></View><Button label="Pilih" variant="lime" onPress={() => void replace(alternative.recipe.id)} /></View>)}</View> : null}
    {item.status !== 'CONSUMED' ? <><View style={styles.chips}>{([1, 0.75, 0.5, 0.25] as const).map((value) => <Chip key={value} label={`${value * 100}%`} selected={fraction === value} onPress={() => setFraction(value)} />)}</View><View style={styles.actions}><Button label="Mulai memasak" icon={ChefHat} variant="secondary" onPress={() => router.push(`/cooking?planId=${plan.id}&itemId=${item.id}` as never)} /><Button label="Tandai dikonsumsi" icon={Utensils} variant="lime" loading={busy} onPress={() => void consume()} /></View></> : null}
  </Card>;
}

export default function GuidedMealScreen() {
  const { current, loading: baselineLoading, error: baselineError, reload: reloadBaseline } = useBaseline(); const [plan, setPlan] = useState<DailyMealPlanRecord | null>(); const [selectedId, setSelectedId] = useState<string>(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>();
  const load = useCallback(async () => { if (!current) return; setLoading(true); setError(undefined); try { const value = await api.getCurrentMealPlan(current.localDate); setPlan(value); setSelectedId((id) => id && value?.items.some((item) => item.id === id) ? id : value?.items.find((item) => item.status !== 'REPLACED')?.id); } catch (cause) { setError(messageFor(cause)); } finally { setLoading(false); } }, [current]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  const generate = async () => { if (!current) return; setLoading(true); setError(undefined); try { setPlan(await api.generateMealPlan(current.localDate)); } catch (cause) { setError(messageFor(cause)); } finally { setLoading(false); } };
  const selected = plan?.items.find((item) => item.id === selectedId);
  return <AppShell title="Guided Meal" subtitle="Rencana menu deterministik untuk hari ini">
    <Card tone="dark" style={styles.hero}><View style={styles.row}><View style={styles.flex}><AppText variant="eyebrow" style={styles.lime}>GUIDED MEAL · REAL</AppText><AppText variant="h1" style={styles.white}>Rencana makan hari ini</AppText><AppText variant="body" style={styles.muted}>Menu yang disarankan untuk membantu memenuhi target program hari ini.</AppText></View><ChefHat size={44} color={colors.lime} /></View></Card>
    {baselineLoading ? <Loading label="Memuat profil…" /> : baselineError ? <ErrorState description={baselineError} onRetry={() => void reloadBaseline()} /> : !current ? <ErrorState title="Baseline belum tersedia" description="Mulai Starter Journey terlebih dahulu." /> : <>
      {error ? <InlineNotice title="Rencana belum tersedia" text={error} tone="danger" /> : null}
      <View style={styles.row}><View><AppText variant="eyebrow">{current.localDate}</AppText><AppText variant="h2">Sisa kebutuhan dan batas</AppText></View><Button label={plan ? 'Buat ulang plan' : 'Buat plan hari ini'} icon={RefreshCw} variant="lime" loading={loading} onPress={() => void generate()} /></View>
      {plan ? <Card tone="mint" style={styles.remaining}><View style={styles.chips}>{(['ENERGY_KCAL', 'PROTEIN_G', 'FIBER_G', 'SODIUM_MG'] as const).map((code) => { const value = plan.remainingNutrition[code]; const remaining = value?.minimumRemaining ?? value?.maximumRemaining; return <Chip key={code} label={`${nutrientLabels[code]} · ${format(remaining, code)}`} tone={remaining === 0 ? 'warning' : 'mint'} />; })}</View><AppText variant="caption">Minimum dan batas atas tetap dibedakan; sisa batas natrium bukan target yang harus dihabiskan.</AppText></Card> : null}
      {loading && !plan ? <Loading label="Menyusun kandidat eligible…" /> : !plan ? <Card><AppText variant="h3">Belum ada rencana</AppText><AppText variant="body">Buat rencana harian dari target, konsumsi hari ini, alergi, preferensi, dan hasil safety.</AppText></Card> : <View style={styles.layout}><View style={styles.list}>{plan.items.filter((item) => item.status !== 'REPLACED').map((item) => <PlanCard key={item.id} plan={plan} item={item} selected={selectedId === item.id} onSelect={() => setSelectedId(item.id)} onReload={load} />)}</View>{selected ? <Card tone="cream" style={styles.side}><View style={styles.row}><Clock3 size={22} color={colors.primary} /><AppText variant="h3">Dampak pilihan</AppText></View>{(['ENERGY_KCAL', 'PROTEIN_G', 'FIBER_G', 'SODIUM_MG'] as const).map((code) => <View key={code} style={styles.metric}><View style={styles.row}><AppText variant="label">{nutrientLabels[code]}</AppText><AppText variant="label">+{format(selected.nutritionImpact[code], code)}</AppText></View><ProgressBar value={selected.nutritionImpact[code] ?? 0} max={Math.max(selected.nutritionImpact[code] ?? 1, plan.remainingNutrition[code]?.minimumRemaining ?? plan.remainingNutrition[code]?.maximumRemaining ?? 1)} label={`${nutrientLabels[code]} dari menu terpilih`} /></View>)}<AppText variant="caption">Snapshot plan tetap menunjuk versi resep dan kebijakan saat plan dibuat.</AppText></Card> : null}</View>}
    </>}
  </AppShell>;
}

const styles = StyleSheet.create({ hero: { padding: spacing.xl }, white: { color: colors.white }, lime: { color: colors.lime }, muted: { color: '#C8D6CC' }, flex: { flex: 1, minWidth: 0, gap: 4 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: spacing.sm }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, remaining: { gap: spacing.sm }, layout: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-start', gap: spacing.md }, list: { flex: 1.55, minWidth: 300, gap: spacing.md }, side: { flex: 0.8, minWidth: 280, gap: spacing.md }, card: { gap: spacing.md }, alternatives: { gap: spacing.sm, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: spacing.sm }, alternative: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.xs }, metric: { gap: spacing.xs } });
