import React, { useCallback, useEffect, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { ArrowLeft, Calculator, Database, History, ShieldCheck } from 'lucide-react-native';
import type { DailyNutritionSummaryRecord, NutritionHistoryRecord } from '@sarira/shared-types';
import { colors, spacing } from '@sarira/design-tokens';
import { AppText, Button, Card, Chip, ErrorState, InlineNotice, Loading, ProgressBar } from '@sarira/ui';
import { AppShell } from '@/layouts/AppShell';
import { api } from '@/services/api';
import { messageFor, useBaseline } from '@/features/baseline/useBaseline';

function daysBefore(localDate: string, amount: number) { const value = new Date(`${localDate}T00:00:00.000Z`); value.setUTCDate(value.getUTCDate() - amount); return value.toISOString().slice(0, 10); }

export default function NutritionScreen() {
  const { current, loading: baselineLoading, error: baselineError } = useBaseline();
  const [summary, setSummary] = useState<DailyNutritionSummaryRecord>(); const [history, setHistory] = useState<NutritionHistoryRecord>();
  const [loading, setLoading] = useState(true); const [recalculating, setRecalculating] = useState(false); const [error, setError] = useState<string>();
  const load = useCallback(async () => { if (!current) return; setLoading(true); setError(undefined); try { const [daily, historyValue] = await Promise.all([api.getDailyNutrition(current.localDate), api.getNutritionHistory(daysBefore(current.localDate, 6), current.localDate)]); setSummary(daily); setHistory(historyValue); } catch (cause) { setError(messageFor(cause)); } finally { setLoading(false); } }, [current]);
  useEffect(() => { if (!current) return; const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [current, load]);
  const recalculate = async () => { setRecalculating(true); try { await api.recalculateNutritionTarget(); await load(); } catch (cause) { setError(messageFor(cause)); } finally { setRecalculating(false); } };
  return <AppShell title="Indikator Nutrisi" subtitle="Minimum, kisaran, dan batas atas dari data nyata">
    {baselineLoading ? <Loading label="Memuat baseline…" /> : baselineError ? <ErrorState description={baselineError} /> : !current ? <ErrorState title="Baseline belum dimulai" description="Nutrition Indicator memerlukan profil dan baseline aktif." /> : loading ? <Loading label="Menghitung ringkasan nutrisi…" /> : error && !summary ? <ErrorState title="Ringkasan belum tersedia" description={error} onRetry={() => void load()} /> : <>
      {error ? <View accessibilityLiveRegion="assertive"><InlineNotice title="Sebagian data belum dimuat" text={error} tone="danger" /></View> : null}
      <Card tone="dark" style={styles.hero}><View style={styles.row}><View style={styles.flex}><AppText variant="eyebrow" style={styles.lime}>NUTRITION ENGINE · {summary?.target?.policyVersion ?? 'TARGET BELUM TERSEDIA'}</AppText><AppText variant="h1" style={styles.white}>Ringkasan {current.localDate}</AppText><AppText variant="body" style={styles.muted}>{summary?.itemCount ?? 0} item · {summary?.mealCount ?? 0} waktu makan · timezone {summary?.timezone}</AppText></View><Calculator size={40} color={colors.lime} /></View><View style={styles.chips}><Chip label="RULE-BASED" tone="lime" /><Chip label="BUKAN DIAGNOSIS" tone="neutral" /><Chip label={summary?.complete ? 'DATA LENGKAP' : 'ADA DATA UNKNOWN'} tone={summary?.complete ? 'mint' : 'warning'} /></View><Button label="Kembali tambah makanan" icon={ArrowLeft} variant="lime" onPress={() => router.push('/food' as never)} /></Card>
      {summary?.target?.restricted ? <InlineNotice title="Target dibatasi oleh safety/usia" text={summary.target.restrictionReasons.join(' · ')} tone="warning" /> : null}
      <View style={styles.indicatorGrid}>{summary?.indicators.map((indicator) => {
        const maximum = indicator.target?.maximum ?? indicator.target?.minimum ?? Math.max(indicator.amount ?? 1, 1);
        return <Card key={indicator.nutrientCode} tone={indicator.status === 'UNAVAILABLE' || indicator.status === 'TARGET_UNAVAILABLE' ? 'cream' : 'white'} style={styles.metric} accessibilityLabel={`${indicator.displayName}. ${indicator.amount === null ? 'Data belum tersedia' : `${indicator.amount} ${indicator.unit}`}. ${indicator.statusLabel}`}><View style={styles.row}><AppText variant="label">{indicator.displayName}</AppText><Chip label={indicator.target?.type.replace('_', ' ') ?? 'TANPA TARGET'} tone={indicator.target?.type === 'UPPER_LIMIT' ? 'warning' : 'neutral'} /></View><AppText variant="h2">{indicator.amount === null ? '—' : indicator.amount.toLocaleString('id-ID')} <AppText variant="caption">{indicator.unit}</AppText></AppText><ProgressBar value={indicator.amount ?? 0} max={maximum} label={`${indicator.displayName}: ${indicator.statusLabel}`} tone={['NEAR_LIMIT', 'OVER_LIMIT', 'ABOVE_RANGE'].includes(indicator.status) ? 'warning' : 'primary'} /><AppText variant="label">{indicator.statusLabel}</AppText>{indicator.target ? <AppText variant="caption">{indicator.target.type === 'MINIMUM' ? `Minimum ${indicator.target.minimum} ${indicator.unit}` : indicator.target.type === 'RANGE' ? `Kisaran ${indicator.target.minimum}–${indicator.target.maximum} ${indicator.unit}` : `Batas ${indicator.target.maximum} ${indicator.unit}`}</AppText> : <AppText variant="caption">Target tidak dibuat untuk kondisi profil saat ini.</AppText>}</Card>;
      })}</View>
      <View style={styles.grid}><Card tone="mint" style={styles.column}><View style={styles.rowStart}><History size={25} color={colors.primary} /><View><AppText variant="h2">Riwayat 7 hari</AppText><AppText variant="caption">Statistik pencatatan tanpa interpretasi sebab-akibat</AppText></View></View>{history?.days.map((day) => <View key={day.localDate} style={styles.historyRow}><View style={styles.flex}><AppText variant="label">{day.localDate}</AppText><AppText variant="caption">{day.itemCount} item · {day.mealCount} waktu makan</AppText></View><AppText variant="label">{day.totals.ENERGY_KCAL === null ? 'Energi belum tersedia' : `${day.totals.ENERGY_KCAL} kcal`}</AppText></View>)}</Card><Card tone="cream" style={styles.column}><View style={styles.rowStart}><ShieldCheck size={25} color={colors.primary} /><View><AppText variant="h2">Target & provenance</AppText><AppText variant="caption">Traceable dan versioned</AppText></View></View><AppText variant="body">Policy: {summary?.target?.policyCode ?? 'Tidak tersedia'} · {summary?.target?.policyVersion ?? '—'}</AppText><AppText variant="body">Alasan kalkulasi: {summary?.target?.calculationReason ?? 'Target dibatasi'}</AppText><AppText variant="body">Safety: {summary?.target?.safetyStatus ?? '—'} · usia: {summary?.target?.ageGroup ?? '—'}</AppText><AppText variant="caption">Policy development memerlukan validasi product/expert dan bukan resep medis.</AppText><Button label="Hitung ulang target" icon={Calculator} variant="secondary" loading={recalculating} onPress={() => void recalculate()} /><View style={styles.rowStart}><Database size={19} color={colors.textMuted} /><AppText variant="caption" style={styles.flex}>Sumber item: {summary?.sourceVersions.length ? summary.sourceVersions.join(', ') : 'Belum ada item.'}</AppText></View></Card></View>
      <InlineNotice title="Guided Meal dan Flex Kitchen tetap Demo" text="Phase 5 menghitung data pangan, porsi, intake, target, dan indikator. Sistem rekomendasi resep atau menu belum dijalankan." tone="info" />
    </>}
  </AppShell>;
}

const styles = StyleSheet.create({ hero: { gap: spacing.lg, padding: spacing.xl, borderColor: colors.primaryDark }, white: { color: colors.white }, lime: { color: colors.lime }, muted: { color: '#C8D6CC' }, flex: { flex: 1, minWidth: 0, gap: 4 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: spacing.sm }, rowStart: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, indicatorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, metric: { width: 280, flexGrow: 1, gap: spacing.sm }, grid: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-start', gap: spacing.md }, column: { flex: 1, minWidth: 300, gap: spacing.md }, historyRow: { minHeight: 64, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: spacing.sm } });
