import React, { useEffect, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, ChefHat, Clock3, ShieldAlert } from 'lucide-react-native';
import type { NutrientCode, RecipeRecord } from '@sarira/shared-types';
import { colors, spacing } from '@sarira/design-tokens';
import { AppText, Button, Card, Chip, ErrorState, InlineNotice, Loading } from '@sarira/ui';
import { AppShell } from '@/layouts/AppShell';
import { messageFor } from '@/features/baseline/useBaseline';
import { api } from '@/services/api';

const nutrientLabels: Record<NutrientCode, string> = { ENERGY_KCAL: 'Energi', PROTEIN_G: 'Protein', CARBOHYDRATE_G: 'Karbohidrat', FAT_G: 'Lemak', SATURATED_FAT_G: 'Lemak jenuh', FIBER_G: 'Serat', SUGAR_G: 'Gula', SODIUM_MG: 'Natrium' };
const format = (amount: number | null | undefined, code: NutrientCode, scale: number) => amount === null || amount === undefined ? 'Data belum tersedia' : `${Math.round(amount * scale * 10) / 10} ${code === 'ENERGY_KCAL' ? 'kcal' : code.endsWith('_MG') ? 'mg' : 'g'}`;

export default function RecipeDetailScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>(); const [recipe, setRecipe] = useState<RecipeRecord>(); const [servingScale, setServingScale] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  useEffect(() => { if (!id) return; const timer = setTimeout(() => void api.getRecipe(id).then(setRecipe).catch((cause) => setError(messageFor(cause))).finally(() => setLoading(false)), 0); return () => clearTimeout(timer); }, [id]);
  return <AppShell title="Detail Resep" subtitle="Bahan, langkah, nutrisi, dan provenance">
    <Button label="Kembali" icon={ArrowLeft} variant="ghost" onPress={() => router.back()} />
    {loading ? <Loading label="Memuat resep…" /> : error ? <ErrorState description={error} /> : !recipe ? <ErrorState title="Resep tidak ditemukan" description="Periksa kembali tautan resep." /> : <>
      <Card tone="lime" style={styles.hero}><View style={styles.row}><View style={styles.flex}><View style={styles.chips}>{recipe.sourceType === 'SYNTHETIC_DEVELOPMENT' ? <Chip label="INTERNAL DEVELOPMENT" tone="warning" /> : null}<Chip label={`Versi ${recipe.currentVersion.version}`} /><Chip label={recipe.verified ? 'TERVERIFIKASI' : 'BELUM TERVERIFIKASI'} tone={recipe.verified ? 'mint' : 'warning'} /></View><AppText variant="h1">{recipe.name}</AppText><AppText variant="body">{recipe.description}</AppText></View><ChefHat size={48} color={colors.primaryDark} /></View></Card>
      {recipe.eligibility?.allergenMessage ? <InlineNotice title="Informasi alergen belum lengkap" text="Jangan menganggap recipe ini aman tanpa memeriksa bahan dan sumbernya." tone="warning" /> : null}
      <View style={styles.layout}><View style={styles.main}><Card style={styles.card}><View style={styles.row}><AppText variant="h2">Bahan</AppText><View style={styles.chips}>{([0.5, 1, 1.5, 2] as const).map((scale) => <Chip key={scale} label={`${scale}× porsi`} selected={servingScale === scale} onPress={() => setServingScale(scale)} />)}</View></View><AppText variant="caption">Penyesuaian porsi mengubah angka dan jumlah bahan; tombol langkah tidak mengubah nutrisi.</AppText>{recipe.currentVersion.ingredients.map((ingredient) => <View key={ingredient.id} style={styles.line}><View style={styles.flex}><AppText variant="label">{ingredient.foodName}</AppText><AppText variant="caption">{ingredient.preparationNote ?? ingredient.food?.category ?? 'Bahan resep'}</AppText></View><AppText variant="label">{Math.round(ingredient.quantity * servingScale * 100) / 100} porsi{ingredient.gramAmount ? ` · ${Math.round(ingredient.gramAmount * servingScale)} g` : ''}</AppText></View>)}</Card>
        <Card tone="cream" style={styles.card}><AppText variant="h2">Langkah memasak</AppText>{recipe.currentVersion.steps.map((step) => <View key={step.id} style={styles.step}><View style={styles.number}><AppText variant="label">{step.orderIndex}</AppText></View><View style={styles.flex}><AppText variant="body">{step.instruction}</AppText>{step.timerSeconds ? <AppText variant="caption">Timer {Math.ceil(step.timerSeconds / 60)} menit</AppText> : null}</View></View>)}</Card></View>
      <View style={styles.side}><Card tone="mint" style={styles.card}><View style={styles.row}><Clock3 size={22} color={colors.primary} /><AppText variant="h3">Ringkasan</AppText></View><View style={styles.chips}><Chip label={`${recipe.currentVersion.prepTimeMinutes} m persiapan`} /><Chip label={`${recipe.currentVersion.cookTimeMinutes} m memasak`} /><Chip label={recipe.currentVersion.difficulty} /><Chip label={`Biaya ${recipe.currentVersion.estimatedCostCategory}`} /></View><AppText variant="caption">Estimasi biaya hanya kategori development, bukan harga real-time.</AppText></Card>
      <Card style={styles.card}><AppText variant="h3">Nutrisi per porsi</AppText><View style={styles.metrics}>{Object.entries(recipe.currentVersion.nutrition?.perServing ?? {}).map(([code, amount]) => <View key={code} style={styles.metric}><AppText variant="caption">{nutrientLabels[code as NutrientCode]}</AppText><AppText variant="label">{format(amount, code as NutrientCode, servingScale)}</AppText></View>)}</View>{recipe.currentVersion.nutrition?.complete ? null : <InlineNotice title="Data tidak lengkap" text="Nilai yang belum tersedia tidak dianggap nol." tone="warning" />}</Card>
      <Card tone="soft" style={styles.card}><View style={styles.row}><ShieldAlert size={22} color={colors.warning} /><AppText variant="h3">Alergen & sumber</AppText></View><View style={styles.chips}>{[...new Set(recipe.currentVersion.ingredients.flatMap((item) => item.food?.allergens.map((allergen) => allergen.code) ?? []))].map((allergen) => <Chip key={allergen} label={allergen} tone="warning" />)}{recipe.currentVersion.dietaryTags.map((tag) => <Chip key={tag} label={tag} tone="mint" />)}</View><AppText variant="caption">Sumber: {recipe.sourceId} · {recipe.sourceVersion}</AppText><AppText variant="caption">{recipe.requiresExpertValidation ? 'REQUIRES EXPERT VALIDATION' : 'Validation status tersedia'}</AppText></Card></View></View>
    </>}
  </AppShell>;
}

const styles = StyleSheet.create({ hero: { padding: spacing.xl }, flex: { flex: 1, minWidth: 0, gap: 4 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: spacing.sm }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, layout: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-start', gap: spacing.md }, main: { flex: 1.5, minWidth: 300, gap: spacing.md }, side: { flex: 0.8, minWidth: 280, gap: spacing.md }, card: { gap: spacing.md }, line: { minHeight: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: spacing.xs }, step: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm }, number: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, metric: { width: '48%', minWidth: 120, padding: spacing.sm, backgroundColor: colors.surfaceSoft, borderRadius: 14, gap: 3 } });
